### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by jokumer**
Adds an usecase for new introduced hook in TemplateService to get away from database sys_template entries for hole typoscript configuration.

### CODE REVIEW

**Comment by marble** [comment]
Thank you very much. Cool, interesting, brandnew. I took the freedom to rework your manuscript. Please check whether it's correct and if you like it.

**Comment by jokumer** [comment]
Like it and learned new things, thanks.

**Comment by marble** [comment]
:-)) Just announced to the world: https://twitter.com/marantern/status/886901977925509121
What's your Twitter name?

**Comment by marble** [comment]
See what good job you did?
There's a lot of response (even more than in this screenshot):

**Pull request merged**
